name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.3
  cupertino_icons: 1.0.2
  intl: ^0.19.0
  flutter_svg_provider: ^1.0.7
  english_words: ^4.0.0
  provider: ^6.0.0
  video_player: ^2.8.3
  custom_video_player: ^1.0.9
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.9
  get: ^4.6.6
  line_awesome_flutter: ^2.0.0
  flashy_tab_bar2: ^0.0.3
  calendar_date_picker2: ^1.0.1
  flutter_bloc: ^8.1.4
  cached_network_image: 3.3.1
  delayed_display: ^2.0.0
  flutter_rating_bar: ^4.0.1
  readmore: ^3.0.0
  expandable_group: ^0.0.6
  flutter_pdfview: ^1.2.7
  flutter_inappwebview: ^6.0.0
  equatable: ^2.0.5
  page_transition: ^2.1.0
  flutter_otp_text_field: ^1.1.3+2
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  firebase_database: ^10.5.5
  youtube_player_flutter:  ^9.0.1
  cloud_firestore: ^4.17.3
  freezed_annotation: ^2.4.1
  foundation: ^0.0.5
  url_launcher: ^6.2.6
  book_my_seat: ^1.0.1
  iconsax: ^0.0.8
  flutter_smart_dialog: ^4.9.6+1

dependency_overrides:
  flutter_svg: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "272727"
  image: assets/images/greeting.png
  image_dark: assets/images/greeting.png
flutter:
  uses-material-design: true
  assets:
    - assets/videos/demo.mp4
    - assets/images/splash.jpg
    - assets/images/google.png
    - assets/images/greeting.png
    - assets/images/svg_selected_bus_seats.svg
    - assets/images/svg_disabled_bus_seat.svg
    - assets/images/svg_sold_bus_seat.svg
    - assets/images/svg_unselected_bus_seat.svg