name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg_provider: ^1.0.7
  english_words: ^4.0.0
  provider: ^6.0.0
  video_player: ^2.8.3
  custom_video_player: ^1.0.9
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.9
  get: ^4.6.6
  line_awesome_flutter: ^2.0.0
  flashy_tab_bar2: ^0.0.3
  flutter_pdfview: ^1.2.7
  realm: ^2.2.0
  mongo_dart: ^0.10.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "272727"
  image: assets/images/greeting.png
  image_dark: assets/images/greeting.png
flutter:
  uses-material-design: true
  assets:
    - assets/videos/demo.mp4
    - assets/images/splash.png
    - assets/images/google.png
    - assets/images/greeting.png