// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBUGfhjSGJu5ud0Q1A1z9j8vXcCQHdWJE',
    appId: '1:858938465366:web:a83d3ba6213258b046aff7',
    messagingSenderId: '858938465366',
    projectId: 'login-8b9e2',
    authDomain: 'login-8b9e2.firebaseapp.com',
    storageBucket: 'login-8b9e2.appspot.com',
    measurementId: 'G-LVZ5YFLY88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCAEuJQemB-UoXc6NZtL6WEWZsquJ2yUk',
    appId: '1:858938465366:android:42fa35877ea615c746aff7',
    messagingSenderId: '858938465366',
    projectId: 'login-8b9e2',
    storageBucket: 'login-8b9e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArUNXl8uSysRBLp9L9ajVi754KnhheXPE',
    appId: '1:858938465366:ios:bfc17a436641a5d746aff7',
    messagingSenderId: '858938465366',
    projectId: 'login-8b9e2',
    storageBucket: 'login-8b9e2.appspot.com',
    iosBundleId: 'com.example.vietnameApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArUNXl8uSysRBLp9L9ajVi754KnhheXPE',
    appId: '1:858938465366:ios:bfc17a436641a5d746aff7',
    messagingSenderId: '858938465366',
    projectId: 'login-8b9e2',
    storageBucket: 'login-8b9e2.appspot.com',
    iosBundleId: 'com.example.vietnameApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBUGfhjSGJu5ud0Q1A1z9j8vXcCQHdWJE',
    appId: '1:858938465366:web:39c8ec61749949c746aff7',
    messagingSenderId: '858938465366',
    projectId: 'login-8b9e2',
    authDomain: 'login-8b9e2.firebaseapp.com',
    storageBucket: 'login-8b9e2.appspot.com',
    measurementId: 'G-65ZTSDWPED',
  );
}
